# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PinataGoCli < Formula
  desc "Official Pinata CLI written in Go"
  homepage "https://github.com/PinataCloud/pinata-go-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PinataCloud/pinata-go-cli/releases/download/v0.1.0/pinata-go-cli_Darwin_x86_64.tar.gz"
      sha256 "b111435659a6cc5613d6c878e1b2a89b5cb4df2e61c642737d73d44f366ccafc"

      def install
        bin.install "pinata-go-cli"
      end
    end
    on_arm do
      url "https://github.com/PinataCloud/pinata-go-cli/releases/download/v0.1.0/pinata-go-cli_Darwin_arm64.tar.gz"
      sha256 "c96e4cbdf221f14a6ff92838526043969afbe78e2eb9ce46ecf8628e99c50cff"

      def install
        bin.install "pinata-go-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/pinata-go-cli/releases/download/v0.1.0/pinata-go-cli_Linux_x86_64.tar.gz"
        sha256 "f14b48344056eda2cd86fad974b69b7a83b542026991ef82c11b508d940faaba"

        def install
          bin.install "pinata-go-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/pinata-go-cli/releases/download/v0.1.0/pinata-go-cli_Linux_arm64.tar.gz"
        sha256 "cc1059796bbcb086c7b91ba1a103c060de69d435eaea73be7464ba457caf3094"

        def install
          bin.install "pinata-go-cli"
        end
      end
    end
  end
end
